services:
  backend:
    build: .
    env_file:
      - .env
    container_name: notes_backend
    ports:
      - "8000:8000"
    networks:
      - notes_net

networks:
  notes_net:
    external: true